// This file is generated by rust-protobuf 2.0.2. Do not edit
// @generated

// https://github.com/Manishearth/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy)]

#![cfg_attr(rustfmt, rustfmt_skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unsafe_code)]
#![allow(unused_imports)]
#![allow(unused_results)]

use protobuf::Message as Message_imported_for_functions;
use protobuf::ProtobufEnum as ProtobufEnum_imported_for_functions;

#[derive(PartialEq,Clone,Default)]
pub struct ProjectProperties {
    // message fields
    pub properties: ::protobuf::RepeatedField<Property>,
    // special fields
    unknown_fields: ::protobuf::UnknownFields,
    cached_size: ::protobuf::CachedSize,
}

impl ProjectProperties {
    pub fn new() -> ProjectProperties {
        ::std::default::Default::default()
    }

    // repeated .google.api.Property properties = 1;

    pub fn clear_properties(&mut self) {
        self.properties.clear();
    }

    // Param is passed by value, moved
    pub fn set_properties(&mut self, v: ::protobuf::RepeatedField<Property>) {
        self.properties = v;
    }

    // Mutable pointer to the field.
    pub fn mut_properties(&mut self) -> &mut ::protobuf::RepeatedField<Property> {
        &mut self.properties
    }

    // Take field
    pub fn take_properties(&mut self) -> ::protobuf::RepeatedField<Property> {
        ::std::mem::replace(&mut self.properties, ::protobuf::RepeatedField::new())
    }

    pub fn get_properties(&self) -> &[Property] {
        &self.properties
    }
}

impl ::protobuf::Message for ProjectProperties {
    fn is_initialized(&self) -> bool {
        for v in &self.properties {
            if !v.is_initialized() {
                return false;
            }
        };
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_repeated_message_into(wire_type, is, &mut self.properties)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        for value in &self.properties {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        };
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream) -> ::protobuf::ProtobufResult<()> {
        for v in &self.properties {
            os.write_tag(1, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        };
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &::std::any::Any {
        self as &::std::any::Any
    }
    fn as_any_mut(&mut self) -> &mut ::std::any::Any {
        self as &mut ::std::any::Any
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<::std::any::Any> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> ProjectProperties {
        ProjectProperties::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::MessageDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_repeated_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<Property>>(
                    "properties",
                    |m: &ProjectProperties| { &m.properties },
                    |m: &mut ProjectProperties| { &mut m.properties },
                ));
                ::protobuf::reflect::MessageDescriptor::new::<ProjectProperties>(
                    "ProjectProperties",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static ProjectProperties {
        static mut instance: ::protobuf::lazy::Lazy<ProjectProperties> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ProjectProperties,
        };
        unsafe {
            instance.get(ProjectProperties::new)
        }
    }
}

impl ::protobuf::Clear for ProjectProperties {
    fn clear(&mut self) {
        self.clear_properties();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for ProjectProperties {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for ProjectProperties {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct Property {
    // message fields
    pub name: ::std::string::String,
    pub field_type: Property_PropertyType,
    pub description: ::std::string::String,
    // special fields
    unknown_fields: ::protobuf::UnknownFields,
    cached_size: ::protobuf::CachedSize,
}

impl Property {
    pub fn new() -> Property {
        ::std::default::Default::default()
    }

    // string name = 1;

    pub fn clear_name(&mut self) {
        self.name.clear();
    }

    // Param is passed by value, moved
    pub fn set_name(&mut self, v: ::std::string::String) {
        self.name = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_name(&mut self) -> &mut ::std::string::String {
        &mut self.name
    }

    // Take field
    pub fn take_name(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.name, ::std::string::String::new())
    }

    pub fn get_name(&self) -> &str {
        &self.name
    }

    // .google.api.Property.PropertyType type = 2;

    pub fn clear_field_type(&mut self) {
        self.field_type = Property_PropertyType::UNSPECIFIED;
    }

    // Param is passed by value, moved
    pub fn set_field_type(&mut self, v: Property_PropertyType) {
        self.field_type = v;
    }

    pub fn get_field_type(&self) -> Property_PropertyType {
        self.field_type
    }

    // string description = 3;

    pub fn clear_description(&mut self) {
        self.description.clear();
    }

    // Param is passed by value, moved
    pub fn set_description(&mut self, v: ::std::string::String) {
        self.description = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_description(&mut self) -> &mut ::std::string::String {
        &mut self.description
    }

    // Take field
    pub fn take_description(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.description, ::std::string::String::new())
    }

    pub fn get_description(&self) -> &str {
        &self.description
    }
}

impl ::protobuf::Message for Property {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.name)?;
                },
                2 => {
                    ::protobuf::rt::read_proto3_enum_with_unknown_fields_into(wire_type, is, &mut self.field_type, 2, &mut self.unknown_fields)?
                },
                3 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.description)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if !self.name.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.name);
        }
        if self.field_type != Property_PropertyType::UNSPECIFIED {
            my_size += ::protobuf::rt::enum_size(2, self.field_type);
        }
        if !self.description.is_empty() {
            my_size += ::protobuf::rt::string_size(3, &self.description);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream) -> ::protobuf::ProtobufResult<()> {
        if !self.name.is_empty() {
            os.write_string(1, &self.name)?;
        }
        if self.field_type != Property_PropertyType::UNSPECIFIED {
            os.write_enum(2, self.field_type.value())?;
        }
        if !self.description.is_empty() {
            os.write_string(3, &self.description)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &::std::any::Any {
        self as &::std::any::Any
    }
    fn as_any_mut(&mut self) -> &mut ::std::any::Any {
        self as &mut ::std::any::Any
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<::std::any::Any> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> Property {
        Property::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::MessageDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                    "name",
                    |m: &Property| { &m.name },
                    |m: &mut Property| { &mut m.name },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeEnum<Property_PropertyType>>(
                    "type",
                    |m: &Property| { &m.field_type },
                    |m: &mut Property| { &mut m.field_type },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                    "description",
                    |m: &Property| { &m.description },
                    |m: &mut Property| { &mut m.description },
                ));
                ::protobuf::reflect::MessageDescriptor::new::<Property>(
                    "Property",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static Property {
        static mut instance: ::protobuf::lazy::Lazy<Property> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const Property,
        };
        unsafe {
            instance.get(Property::new)
        }
    }
}

impl ::protobuf::Clear for Property {
    fn clear(&mut self) {
        self.clear_name();
        self.clear_field_type();
        self.clear_description();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for Property {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for Property {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Message(self)
    }
}

#[derive(Clone,PartialEq,Eq,Debug,Hash)]
pub enum Property_PropertyType {
    UNSPECIFIED = 0,
    INT64 = 1,
    BOOL = 2,
    STRING = 3,
    DOUBLE = 4,
}

impl ::protobuf::ProtobufEnum for Property_PropertyType {
    fn value(&self) -> i32 {
        *self as i32
    }

    fn from_i32(value: i32) -> ::std::option::Option<Property_PropertyType> {
        match value {
            0 => ::std::option::Option::Some(Property_PropertyType::UNSPECIFIED),
            1 => ::std::option::Option::Some(Property_PropertyType::INT64),
            2 => ::std::option::Option::Some(Property_PropertyType::BOOL),
            3 => ::std::option::Option::Some(Property_PropertyType::STRING),
            4 => ::std::option::Option::Some(Property_PropertyType::DOUBLE),
            _ => ::std::option::Option::None
        }
    }

    fn values() -> &'static [Self] {
        static values: &'static [Property_PropertyType] = &[
            Property_PropertyType::UNSPECIFIED,
            Property_PropertyType::INT64,
            Property_PropertyType::BOOL,
            Property_PropertyType::STRING,
            Property_PropertyType::DOUBLE,
        ];
        values
    }

    fn enum_descriptor_static() -> &'static ::protobuf::reflect::EnumDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::EnumDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::EnumDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                ::protobuf::reflect::EnumDescriptor::new("Property_PropertyType", file_descriptor_proto())
            })
        }
    }
}

impl ::std::marker::Copy for Property_PropertyType {
}

impl ::std::default::Default for Property_PropertyType {
    fn default() -> Self {
        Property_PropertyType::UNSPECIFIED
    }
}

impl ::protobuf::reflect::ProtobufValue for Property_PropertyType {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Enum(self.descriptor())
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x19google/api/consumer.proto\x12\ngoogle.api\"I\n\x11ProjectPropertie\
    s\x124\n\nproperties\x18\x01\x20\x03(\x0b2\x14.google.api.PropertyR\npro\
    perties\"\xc5\x01\n\x08Property\x12\x12\n\x04name\x18\x01\x20\x01(\tR\
    \x04name\x125\n\x04type\x18\x02\x20\x01(\x0e2!.google.api.Property.Prope\
    rtyTypeR\x04type\x12\x20\n\x0bdescription\x18\x03\x20\x01(\tR\x0bdescrip\
    tion\"L\n\x0cPropertyType\x12\x0f\n\x0bUNSPECIFIED\x10\0\x12\t\n\x05INT6\
    4\x10\x01\x12\x08\n\x04BOOL\x10\x02\x12\n\n\x06STRING\x10\x03\x12\n\n\
    \x06DOUBLE\x10\x04Bh\n\x0ecom.google.apiB\rConsumerProtoP\x01ZEgoogle.go\
    lang.org/genproto/googleapis/api/serviceconfig;serviceconfigJ\xdd\x17\n\
    \x06\x12\x04\x0e\0R\x01\n\xbd\x04\n\x01\x0c\x12\x03\x0e\0\x122\xb2\x04\
    \x20Copyright\x202016\x20Google\x20Inc.\n\n\x20Licensed\x20under\x20the\
    \x20Apache\x20License,\x20Version\x202.0\x20(the\x20\"License\");\n\x20y\
    ou\x20may\x20not\x20use\x20this\x20file\x20except\x20in\x20compliance\
    \x20with\x20the\x20License.\n\x20You\x20may\x20obtain\x20a\x20copy\x20of\
    \x20the\x20License\x20at\n\n\x20\x20\x20\x20\x20http://www.apache.org/li\
    censes/LICENSE-2.0\n\n\x20Unless\x20required\x20by\x20applicable\x20law\
    \x20or\x20agreed\x20to\x20in\x20writing,\x20software\n\x20distributed\
    \x20under\x20the\x20License\x20is\x20distributed\x20on\x20an\x20\"AS\x20\
    IS\"\x20BASIS,\n\x20WITHOUT\x20WARRANTIES\x20OR\x20CONDITIONS\x20OF\x20A\
    NY\x20KIND,\x20either\x20express\x20or\x20implied.\n\x20See\x20the\x20Li\
    cense\x20for\x20the\x20specific\x20language\x20governing\x20permissions\
    \x20and\n\x20limitations\x20under\x20the\x20License.\n\n\x08\n\x01\x02\
    \x12\x03\x10\x08\x12\n\x08\n\x01\x08\x12\x03\x12\0\\\n\x0b\n\x04\x08\xe7\
    \x07\0\x12\x03\x12\0\\\n\x0c\n\x05\x08\xe7\x07\0\x02\x12\x03\x12\x07\x11\
    \n\r\n\x06\x08\xe7\x07\0\x02\0\x12\x03\x12\x07\x11\n\x0e\n\x07\x08\xe7\
    \x07\0\x02\0\x01\x12\x03\x12\x07\x11\n\x0c\n\x05\x08\xe7\x07\0\x07\x12\
    \x03\x12\x14[\n\x08\n\x01\x08\x12\x03\x13\0\"\n\x0b\n\x04\x08\xe7\x07\
    \x01\x12\x03\x13\0\"\n\x0c\n\x05\x08\xe7\x07\x01\x02\x12\x03\x13\x07\x1a\
    \n\r\n\x06\x08\xe7\x07\x01\x02\0\x12\x03\x13\x07\x1a\n\x0e\n\x07\x08\xe7\
    \x07\x01\x02\0\x01\x12\x03\x13\x07\x1a\n\x0c\n\x05\x08\xe7\x07\x01\x03\
    \x12\x03\x13\x1d!\n\x08\n\x01\x08\x12\x03\x14\0.\n\x0b\n\x04\x08\xe7\x07\
    \x02\x12\x03\x14\0.\n\x0c\n\x05\x08\xe7\x07\x02\x02\x12\x03\x14\x07\x1b\
    \n\r\n\x06\x08\xe7\x07\x02\x02\0\x12\x03\x14\x07\x1b\n\x0e\n\x07\x08\xe7\
    \x07\x02\x02\0\x01\x12\x03\x14\x07\x1b\n\x0c\n\x05\x08\xe7\x07\x02\x07\
    \x12\x03\x14\x1e-\n\x08\n\x01\x08\x12\x03\x15\0'\n\x0b\n\x04\x08\xe7\x07\
    \x03\x12\x03\x15\0'\n\x0c\n\x05\x08\xe7\x07\x03\x02\x12\x03\x15\x07\x13\
    \n\r\n\x06\x08\xe7\x07\x03\x02\0\x12\x03\x15\x07\x13\n\x0e\n\x07\x08\xe7\
    \x07\x03\x02\0\x01\x12\x03\x15\x07\x13\n\x0c\n\x05\x08\xe7\x07\x03\x07\
    \x12\x03\x15\x16&\n\xbf\x05\n\x02\x04\0\x12\x04(\0+\x01\x1a\xb2\x05\x20A\
    \x20descriptor\x20for\x20defining\x20project\x20properties\x20for\x20a\
    \x20service.\x20One\x20service\x20may\n\x20have\x20many\x20consumer\x20p\
    rojects,\x20and\x20the\x20service\x20may\x20want\x20to\x20behave\x20diff\
    erently\n\x20depending\x20on\x20some\x20properties\x20on\x20the\x20proje\
    ct.\x20For\x20example,\x20a\x20project\x20may\x20be\n\x20associated\x20w\
    ith\x20a\x20school,\x20or\x20a\x20business,\x20or\x20a\x20government\x20\
    agency,\x20a\x20business\n\x20type\x20property\x20on\x20the\x20project\
    \x20may\x20affect\x20how\x20a\x20service\x20responds\x20to\x20the\x20cli\
    ent.\n\x20This\x20descriptor\x20defines\x20which\x20properties\x20are\
    \x20allowed\x20to\x20be\x20set\x20on\x20a\x20project.\n\n\x20Example:\n\
    \n\x20\x20\x20\x20project_properties:\n\x20\x20\x20\x20\x20\x20propertie\
    s:\n\x20\x20\x20\x20\x20\x20-\x20name:\x20NO_WATERMARK\n\x20\x20\x20\x20\
    \x20\x20\x20\x20type:\x20BOOL\n\x20\x20\x20\x20\x20\x20\x20\x20descripti\
    on:\x20Allows\x20usage\x20of\x20the\x20API\x20without\x20watermarks.\n\
    \x20\x20\x20\x20\x20\x20-\x20name:\x20EXTENDED_TILE_CACHE_PERIOD\n\x20\
    \x20\x20\x20\x20\x20\x20\x20type:\x20INT64\n\n\n\n\x03\x04\0\x01\x12\x03\
    (\x08\x19\n@\n\x04\x04\0\x02\0\x12\x03*\x02#\x1a3\x20List\x20of\x20per\
    \x20consumer\x20project-specific\x20properties.\n\n\x0c\n\x05\x04\0\x02\
    \0\x04\x12\x03*\x02\n\n\x0c\n\x05\x04\0\x02\0\x06\x12\x03*\x0b\x13\n\x0c\
    \n\x05\x04\0\x02\0\x01\x12\x03*\x14\x1e\n\x0c\n\x05\x04\0\x02\0\x03\x12\
    \x03*!\"\n\xe1\x03\n\x02\x04\x01\x12\x047\0R\x01\x1a\xd4\x03\x20Defines\
    \x20project\x20properties.\n\n\x20API\x20services\x20can\x20define\x20pr\
    operties\x20that\x20can\x20be\x20assigned\x20to\x20consumer\x20projects\
    \n\x20so\x20that\x20backends\x20can\x20perform\x20response\x20customizat\
    ion\x20without\x20having\x20to\x20make\n\x20additional\x20calls\x20or\
    \x20maintain\x20additional\x20storage.\x20For\x20example,\x20Maps\x20API\
    \n\x20defines\x20properties\x20that\x20controls\x20map\x20tile\x20cache\
    \x20period,\x20or\x20whether\x20to\x20embed\x20a\n\x20watermark\x20in\
    \x20a\x20result.\n\n\x20These\x20values\x20can\x20be\x20set\x20via\x20AP\
    I\x20producer\x20console.\x20Only\x20API\x20providers\x20can\n\x20define\
    \x20and\x20set\x20these\x20properties.\n\n\n\n\x03\x04\x01\x01\x12\x037\
    \x08\x10\n:\n\x04\x04\x01\x04\0\x12\x049\x02H\x03\x1a,\x20Supported\x20d\
    ata\x20type\x20of\x20the\x20property\x20values\n\n\x0c\n\x05\x04\x01\x04\
    \0\x01\x12\x039\x07\x13\nF\n\x06\x04\x01\x04\0\x02\0\x12\x03;\x04\x14\
    \x1a7\x20The\x20type\x20is\x20unspecified,\x20and\x20will\x20result\x20i\
    n\x20an\x20error.\n\n\x0e\n\x07\x04\x01\x04\0\x02\0\x01\x12\x03;\x04\x0f\
    \n\x0e\n\x07\x04\x01\x04\0\x02\0\x02\x12\x03;\x12\x13\n%\n\x06\x04\x01\
    \x04\0\x02\x01\x12\x03>\x04\x0e\x1a\x16\x20The\x20type\x20is\x20`int64`.\
    \n\n\x0e\n\x07\x04\x01\x04\0\x02\x01\x01\x12\x03>\x04\t\n\x0e\n\x07\x04\
    \x01\x04\0\x02\x01\x02\x12\x03>\x0c\r\n$\n\x06\x04\x01\x04\0\x02\x02\x12\
    \x03A\x04\r\x1a\x15\x20The\x20type\x20is\x20`bool`.\n\n\x0e\n\x07\x04\
    \x01\x04\0\x02\x02\x01\x12\x03A\x04\x08\n\x0e\n\x07\x04\x01\x04\0\x02\
    \x02\x02\x12\x03A\x0b\x0c\n&\n\x06\x04\x01\x04\0\x02\x03\x12\x03D\x04\
    \x0f\x1a\x17\x20The\x20type\x20is\x20`string`.\n\n\x0e\n\x07\x04\x01\x04\
    \0\x02\x03\x01\x12\x03D\x04\n\n\x0e\n\x07\x04\x01\x04\0\x02\x03\x02\x12\
    \x03D\r\x0e\n&\n\x06\x04\x01\x04\0\x02\x04\x12\x03G\x04\x0f\x1a\x17\x20T\
    he\x20type\x20is\x20'double'.\n\n\x0e\n\x07\x04\x01\x04\0\x02\x04\x01\
    \x12\x03G\x04\n\n\x0e\n\x07\x04\x01\x04\0\x02\x04\x02\x12\x03G\r\x0e\n4\
    \n\x04\x04\x01\x02\0\x12\x03K\x02\x12\x1a'\x20The\x20name\x20of\x20the\
    \x20property\x20(a.k.a\x20key).\n\n\r\n\x05\x04\x01\x02\0\x04\x12\x04K\
    \x02H\x03\n\x0c\n\x05\x04\x01\x02\0\x05\x12\x03K\x02\x08\n\x0c\n\x05\x04\
    \x01\x02\0\x01\x12\x03K\t\r\n\x0c\n\x05\x04\x01\x02\0\x03\x12\x03K\x10\
    \x11\n)\n\x04\x04\x01\x02\x01\x12\x03N\x02\x18\x1a\x1c\x20The\x20type\
    \x20of\x20this\x20property.\n\n\r\n\x05\x04\x01\x02\x01\x04\x12\x04N\x02\
    K\x12\n\x0c\n\x05\x04\x01\x02\x01\x06\x12\x03N\x02\x0e\n\x0c\n\x05\x04\
    \x01\x02\x01\x01\x12\x03N\x0f\x13\n\x0c\n\x05\x04\x01\x02\x01\x03\x12\
    \x03N\x16\x17\n.\n\x04\x04\x01\x02\x02\x12\x03Q\x02\x19\x1a!\x20The\x20d\
    escription\x20of\x20the\x20property\n\n\r\n\x05\x04\x01\x02\x02\x04\x12\
    \x04Q\x02N\x18\n\x0c\n\x05\x04\x01\x02\x02\x05\x12\x03Q\x02\x08\n\x0c\n\
    \x05\x04\x01\x02\x02\x01\x12\x03Q\t\x14\n\x0c\n\x05\x04\x01\x02\x02\x03\
    \x12\x03Q\x17\x18b\x06proto3\
";

static mut file_descriptor_proto_lazy: ::protobuf::lazy::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::lazy::Lazy {
    lock: ::protobuf::lazy::ONCE_INIT,
    ptr: 0 as *const ::protobuf::descriptor::FileDescriptorProto,
};

fn parse_descriptor_proto() -> ::protobuf::descriptor::FileDescriptorProto {
    ::protobuf::parse_from_bytes(file_descriptor_proto_data).unwrap()
}

pub fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    unsafe {
        file_descriptor_proto_lazy.get(|| {
            parse_descriptor_proto()
        })
    }
}
